temp.componant_type = 1;
    temp.componant_in_connect = 2;
    temp.componant_out_connect = 6;
    temp.componant_value_polar = 0;
    temp.componant_value_rectangular = 0;
    componants.push_back(temp);
    temp.componant_type = 2;
    temp.componant_in_connect = 6;
    temp.componant_out_connect = 10;
    temp.componant_value_polar = 27;
    temp.componant_value_rectangular = 27;
    componants.push_back(temp);
    temp.componant_type = 1;
    temp.componant_in_connect = 10;
    temp.componant_out_connect = 14;
    temp.componant_value_polar = 0;
    temp.componant_value_rectangular = 0;
    componants.push_back(temp);
    temp.componant_type = 2;
    temp.componant_in_connect = 14;
    temp.componant_out_connect = 18;
    temp.componant_value_polar = 54;
    temp.componant_value_rectangular = 54;
    componants.push_back(temp);
    temp.componant_type = 1;
    temp.componant_in_connect = 18;
    temp.componant_out_connect = 22;
    temp.componant_value_polar = 0;
    temp.componant_value_rectangular = 0;
    componants.push_back(temp);
    voltage_scource.voltage_scourc_in_connect = 2;
    voltage_scource.voltage_scourc_out_connect = 22;
    cout << analysis(componants, voltage_scource) << endl;
    componants.clear();